# **Data preprocessing notebook**

This notebook focuses on building a clean and consistent preprocessing pipeline for the Lending Club dataset (obtained from Kaggle). The goal is to transform the raw loan-level data into a structured, modeling-ready dataset suitable for estimating Expected Loss (EL) — a key risk metric used by financial institutions to quantify credit risk.

LendingClub is a U.S.-based peer-to-peer (P2P) lending platform headquartered in San Francisco. It was the first P2P lender to register its loan offerings as securities with the U.S. Securities and Exchange Commission (SEC) and the first to provide a secondary market for loan trading. Over the years, it has grown into the world’s largest P2P lending platform, making its publicly available loan-level data a valuable resource for credit-risk research and model development.

In [ ]:
import sys
import pandas as pd
import numpy as np
import sklearn

from sklearn import __version__ as sklearn_version
from datetime import datetime

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
print(f'Python {sys.version.split()[0]}')
print(f'pandas=={pd.__version__}')
print(f'numpy=={np.__version__}')
print(f'sklearn=={sklearn_version}')

Python 3.12.12
pandas==2.2.2
numpy==2.0.2
sklearn==1.6.1

In [ ]:
df = pd.read_csv('raw-data/loan_data.csv')
df.head()

/tmp/ipython-input-3061870695.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/ML Zoomcamp 2025/Projects/Projetc 3 (EL estimation)/loan_data.csv')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000.0,5000.0,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,1.0,NaN,NaN,3.0,0.0,13648.0,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-2015,171.62,NaN,Jan-2016,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500.0,2500.0,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-1999,5.0,NaN,NaN,3.0,0.0,1687.0,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-2013,119.66,NaN,Sep-2013,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400.0,2400.0,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,2.0,NaN,NaN,2.0,0.0,2956.0,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-2014,649.91,NaN,Jan-2016,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000.0,10000.0,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-2011,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-1996,1.0,35.0,NaN,10.0,0.0,5598.0,21.0,37.0,f,0.0,0.0,12226.302212,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-2015,357.48,NaN,Jan-2015,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000.0,3000.0,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-2011,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-1996,0.0,38.0,NaN,15.0,0.0,27783.0,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-2016,67.79,Feb-2016,Jan-2016,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           466285 non-null  int64
 1   member_id                    466285 non-null  int64
 2   loan_amnt                    466285 non-null  float64
 3   funded_amnt                  466285 non-null  float64
 4   funded_amnt_inv              466285 non-null  float64
 5   term                         466285 non-null  object
 6   int_rate                     466285 non-null  float64
 7   installment                  466285 non-null  float64
 8   grade                        466285 non-null  object
 9   sub_grade                    466285 non-null  object
 10  emp_title                    438697 non-null  object
 11  emp_length                   445277 non-null  object
 12  home_ownership               466285 non-null  object
 13  annual_inc                   466281 non-null  float64
 14  verification_status          466285 non-null  object
 15  issue_d                      466285 non-null  object
 16  loan_status                  466285 non-null  object
 17  pymnt_plan                   466285 non-null  object
 18  url                          466285 non-null  object
 19  desc                         125981 non-null  object
 20  purpose                      466285 non-null  object
 21  title                        466264 non-null  object
 22  zip_code                     466285 non-null  object
 23  addr_state                   466285 non-null  object
 24  dti                          466285 non-null  float64
 25  delinq_2yrs                  466256 non-null  float64
 26  earliest_cr_line             466256 non-null  object
 27  inq_last_6mths               466256 non-null  float64
 28  mths_since_last_delinq       215934 non-null  float64
 29  mths_since_last_record       62638 non-null   float64
 30  open_acc                     466256 non-null  float64
 31  pub_rec                      466256 non-null  float64
 32  revol_bal                    466285 non-null  float64
 33  revol_util                   465945 non-null  float64
 34  total_acc                    466256 non-null  float64
 35  initial_list_status          466285 non-null  object
 36  out_prncp                    466285 non-null  float64
 37  out_prncp_inv                466285 non-null  float64
 38  total_pymnt                  466285 non-null  float64
 39  total_pymnt_inv              466285 non-null  float64
 40  total_rec_prncp              466285 non-null  float64
 41  total_rec_int                466285 non-null  float64
 42  total_rec_late_fee           466285 non-null  float64
 43  recoveries                   466285 non-null  float64
 44  collection_recovery_fee      466285 non-null  float64
 45  last_pymnt_d                 465909 non-null  object
 46  last_pymnt_amnt              466285 non-null  float64
 47  next_pymnt_d                 239071 non-null  object
 48  last_credit_pull_d           466243 non-null  object
 49  collections_12_mths_ex_med   466140 non-null  float64
 50  mths_since_last_major_derog  98974 non-null   float64
 51  policy_code                  466285 non-null  float64
 52  application_type             466285 non-null  object
 53  annual_inc_joint             0 non-null       float64
 54  dti_joint                    0 non-null       float64
 55  verification_status_joint    0 non-null       float64
 56  acc_now_delinq               466256 non-null  float64
 57  tot_coll_amt                 396009 non-null  float64
 58  tot_cur_bal                  396009 non-null  float64
 59  open_acc_6m                  0 non-null       float64
 60  open_il_6m                   0 non-null       float64
 61  open_il_12m                  0 non-null       float64
 62  open_il_24m                  0 non-null       float64
 63  mths_since_rcnt_il           0 non-null       float64
 64  total_bal_il                 0 non-null       float64
 65  il_util                      0 non-null       float64
 66  open_rv_12m                  0 non-null       float64
 67  open_rv_24m                  0 non-null       float64
 68  max_bal_bc                   0 non-null       float64
 69  all_util                     0 non-null       float64
 70  total_rev_hi_lim             396009 non-null  float64
 71  inq_fi                       0 non-null       float64
 72  total_cu_tl                  0 non-null       float64
 73  inq_last_12m                 0 non-null       float64
dtypes: float64(50), int64(2), object(22)
memory usage: 263.3+ MB

We will not use all variables provided in the dataset; instead, we focus on a curated subset of features that are most relevant for credit-risk modeling and Expected Loss estimation.

The selected variables are:

`id` — Unique loan identifier.

`member_id` — Identifier of the borrower requesting the loan.

`loan_amnt` — Amount originally requested by the borrower.

`funded_amnt` — Total amount funded for the loan at that point in time.

`term` — Loan maturity in months (36 or 60).

`int_rate` — Interest rate assigned to the loan.

`installment` — Monthly payment owed by the borrower if the loan is funded.

`grade` — Credit grade assigned by LendingClub’s internal rating system.

`emp_length` — Borrower’s employment length (in years).

`home_ownership` — Borrower's home-ownership status at application.

`annual_inc` — Self-reported annual income.

`issue_d` — Month when the loan was issued.

`loan_status` — Current loan status (used to derive our target variable).

`purpose` — Borrower-provided purpose for the loan.

`addr_state` — U.S. state of residence provided in the application.

`dti` — Debt-to-income ratio, excluding mortgage and requested loan.

`delinq_2yrs` — Number of 30+ day delinquencies in the past 2 years.

`earliest_cr_line` — Date of the borrower’s earliest reported credit line.

`verification_status` — Whether income was verified by LendingClub.

`initial_list_status` — Initial listing status of the loan (W/F).

`inq_last_6mths` — Number of credit inquiries in the last 6 months.

`open_acc` — Number of currently open credit accounts.

`pub_rec` — Number of derogatory public records.

`total_acc` — Total number of credit accounts on file.

`acc_now_delinq` — Number of accounts currently delinquent.

`total_rev_hi_lim` — Total revolving high credit limit.

`recoveries` — The amount the lender managed to recover after a borrower defaulted (“post charge-off gross recovery”).

`total_rec_prncp` — The total principal amount that has been repaid to date on the loan.

In [ ]:
selected_cols = [
    "id", "member_id", "loan_amnt", "funded_amnt", "term", "int_rate", "installment", "grade", "emp_length",
    "home_ownership", "annual_inc", "issue_d", "loan_status", "purpose", "addr_state", "dti", "delinq_2yrs",
    "earliest_cr_line", "verification_status", "initial_list_status", "inq_last_6mths", "open_acc", "pub_rec",
    "total_acc", "acc_now_delinq", "total_rev_hi_lim", 'recoveries', 'total_rec_prncp'
]
df = df.loc[:, selected_cols]
df.head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,issue_d,loan_status,purpose,addr_state,dti,delinq_2yrs,earliest_cr_line,verification_status,initial_list_status,inq_last_6mths,open_acc,pub_rec,total_acc,acc_now_delinq,total_rev_hi_lim,recoveries,total_rec_prncp
0,1077501,1296599,5000.0,5000.0,36 months,10.65,162.87,B,10+ years,RENT,24000.0,Dec-2011,Fully Paid,credit_card,AZ,27.65,0.0,Jan-1985,Verified,f,1.0,3.0,0.0,9.0,0.0,NaN,0.00,5000.00
1,1077430,1314167,2500.0,2500.0,60 months,15.27,59.83,C,< 1 year,RENT,30000.0,Dec-2011,Charged Off,car,GA,1.00,0.0,Apr-1999,Source Verified,f,5.0,3.0,0.0,4.0,0.0,NaN,117.08,456.46
2,1077175,1313524,2400.0,2400.0,36 months,15.96,84.33,C,10+ years,RENT,12252.0,Dec-2011,Fully Paid,small_business,IL,8.72,0.0,Nov-2001,Not Verified,f,2.0,2.0,0.0,10.0,0.0,NaN,0.00,2400.00
3,1076863,1277178,10000.0,10000.0,36 months,13.49,339.31,C,10+ years,RENT,49200.0,Dec-2011,Fully Paid,other,CA,20.00,0.0,Feb-1996,Source Verified,f,1.0,10.0,0.0,37.0,0.0,NaN,0.00,10000.00
4,1075358,1311748,3000.0,3000.0,60 months,12.69,67.79,B,1 year,RENT,80000.0,Dec-2011,Current,other,OR,17.94,0.0,Jan-1996,Source Verified,f,0.0,15.0,0.0,38.0,0.0,NaN,0.00,2233.10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 28 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   466285 non-null  int64
 1   member_id            466285 non-null  int64
 2   loan_amnt            466285 non-null  float64
 3   funded_amnt          466285 non-null  float64
 4   term                 466285 non-null  object
 5   int_rate             466285 non-null  float64
 6   installment          466285 non-null  float64
 7   grade                466285 non-null  object
 8   emp_length           445277 non-null  object
 9   home_ownership       466285 non-null  object
 10  annual_inc           466281 non-null  float64
 11  issue_d              466285 non-null  object
 12  loan_status          466285 non-null  object
 13  purpose              466285 non-null  object
 14  addr_state           466285 non-null  object
 15  dti                  466285 non-null  float64
 16  delinq_2yrs          466256 non-null  float64
 17  earliest_cr_line     466256 non-null  object
 18  verification_status  466285 non-null  object
 19  initial_list_status  466285 non-null  object
 20  inq_last_6mths       466256 non-null  float64
 21  open_acc             466256 non-null  float64
 22  pub_rec              466256 non-null  float64
 23  total_acc            466256 non-null  float64
 24  acc_now_delinq       466256 non-null  float64
 25  total_rev_hi_lim     396009 non-null  float64
 26  recoveries           466285 non-null  float64
 27  total_rec_prncp      466285 non-null  float64
dtypes: float64(15), int64(2), object(11)
memory usage: 99.6+ MB

In [ ]:
df.iloc[0, :]

id                         1077501
member_id                  1296599
loan_amnt                   5000.0
funded_amnt                 5000.0
term                     36 months
int_rate                     10.65
installment                 162.87
grade                            B
emp_length               10+ years
home_ownership                RENT
annual_inc                 24000.0
issue_d                   Dec-2011
loan_status             Fully Paid
purpose                credit_card
addr_state                      AZ
dti                          27.65
delinq_2yrs                    0.0
earliest_cr_line          Jan-1985
verification_status       Verified
initial_list_status              f
inq_last_6mths                 1.0
open_acc                       3.0
pub_rec                        0.0
total_acc                      9.0
acc_now_delinq                 0.0
total_rev_hi_lim               NaN
recoveries                     0.0
total_rec_prncp             5000.0
Name: 0, dtype: object

Before modeling, several columns require attention due to unusable formats, inconsistent data types, or information that is not relevant for our analysis.
Therefore, the first step is to clean and normalize the dataset, ensuring that all selected variables are structured, interpretable, and ready for downstream processing.

In [ ]:
df["emp_length"].value_counts()

emp_length
10+ years    150049
2 years       41373
3 years       36596
< 1 year      36265
5 years       30774
1 year        29622
4 years       28023
7 years       26180
6 years       26112
8 years       22395
9 years       17888
Name: count, dtype: int64

In [ ]:
df.loc[~df["emp_length"].isnull(), "emp_length"] = (
    df.loc[
        ~df["emp_length"].isnull(), "emp_length"
    ].astype(str)
     .str.extract(r"([^(?:years?)]*)").iloc[:, 0]
     .str.replace(r"10\+", str(10), regex=True)
     .str.replace(r"< 1", str(0), regex=True)
     .astype(int)
)

In [ ]:
df["emp_length"].value_counts()

emp_length
10    150049
2      41373
3      36596
0      36265
5      30774
1      29622
4      28023
7      26180
6      26112
8      22395
9      17888
Name: count, dtype: int64

In [ ]:
df["term"].value_counts()

term
36 months    337953
60 months    128332
Name: count, dtype: int64

In [ ]:
df.loc[:, "term"] = (
    df.loc[
        :, "term"
    ].astype(str)
     .str.extract(r"(\d+)").iloc[:, 0]
     .astype(int)
)

In [ ]:
df["term"].value_counts()

term
36    337953
60    128332
Name: count, dtype: int64

In [ ]:
df["issue_d"].value_counts()

issue_d
Oct-2014    38782
Jul-2014    29306
Nov-2014    25054
May-2014    19099
Apr-2014    19071
Aug-2014    18814
Jun-2014    17179
Mar-2014    16513
Jan-2014    15628
Feb-2014    15269
Dec-2013    15020
Nov-2013    14676
Oct-2013    14114
Sep-2013    12987
Aug-2013    12674
Jul-2013    11910
Jun-2013    10899
Sep-2014    10606
May-2013    10350
Dec-2014    10307
Apr-2013     9419
Mar-2013     8273
Feb-2013     7561
Jan-2013     6872
Nov-2012     6382
Oct-2012     6263
Sep-2012     6087
Dec-2012     6066
Aug-2012     5419
Jul-2012     4627
Jun-2012     3817
May-2012     3400
Apr-2012     3230
Mar-2012     2914
Jan-2012     2602
Feb-2012     2560
Dec-2011     2267
Nov-2011     2232
Oct-2011     2118
Sep-2011     2067
Aug-2011     1934
Jul-2011     1875
Jun-2011     1835
May-2011     1704
Apr-2011     1563
Mar-2011     1448
Jan-2011     1380
Dec-2010     1335
Feb-2011     1298
Oct-2010     1232
Nov-2010     1224
Jul-2010     1204
Sep-2010     1189
Aug-2010     1175
Jun-2010     1105
May-2010      989
Apr-2010      912
Mar-2010      828
Feb-2010      682
Nov-2009      662
Jan-2010      662
Dec-2009      658
Oct-2009      604
Sep-2009      507
Aug-2009      446
Jul-2009      411
Jun-2009      406
Mar-2008      402
May-2009      359
Apr-2009      333
Mar-2009      324
Feb-2008      306
Jan-2008      305
Feb-2009      302
Jan-2009      269
Apr-2008      259
Dec-2008      253
Nov-2008      209
Dec-2007      172
Jul-2008      141
Jun-2008      124
Oct-2008      122
May-2008      115
Nov-2007      112
Oct-2007      105
Aug-2008      100
Aug-2007       74
Jul-2007       63
Sep-2008       57
Sep-2007       53
Jun-2007       24
Name: count, dtype: int64

In [ ]:
df["issue_d"] = pd.to_datetime(df["issue_d"], format="%b-%Y")

In [ ]:
df["issue_d"].value_counts()

issue_d
2014-10-01    38782
2014-07-01    29306
2014-11-01    25054
2014-05-01    19099
2014-04-01    19071
2014-08-01    18814
2014-06-01    17179
2014-03-01    16513
2014-01-01    15628
2014-02-01    15269
2013-12-01    15020
2013-11-01    14676
2013-10-01    14114
2013-09-01    12987
2013-08-01    12674
2013-07-01    11910
2013-06-01    10899
2014-09-01    10606
2013-05-01    10350
2014-12-01    10307
2013-04-01     9419
2013-03-01     8273
2013-02-01     7561
2013-01-01     6872
2012-11-01     6382
2012-10-01     6263
2012-09-01     6087
2012-12-01     6066
2012-08-01     5419
2012-07-01     4627
2012-06-01     3817
2012-05-01     3400
2012-04-01     3230
2012-03-01     2914
2012-01-01     2602
2012-02-01     2560
2011-12-01     2267
2011-11-01     2232
2011-10-01     2118
2011-09-01     2067
2011-08-01     1934
2011-07-01     1875
2011-06-01     1835
2011-05-01     1704
2011-04-01     1563
2011-03-01     1448
2011-01-01     1380
2010-12-01     1335
2011-02-01     1298
2010-10-01     1232
2010-11-01     1224
2010-07-01     1204
2010-09-01     1189
2010-08-01     1175
2010-06-01     1105
2010-05-01      989
2010-04-01      912
2010-03-01      828
2010-02-01      682
2009-11-01      662
2010-01-01      662
2009-12-01      658
2009-10-01      604
2009-09-01      507
2009-08-01      446
2009-07-01      411
2009-06-01      406
2008-03-01      402
2009-05-01      359
2009-04-01      333
2009-03-01      324
2008-02-01      306
2008-01-01      305
2009-02-01      302
2009-01-01      269
2008-04-01      259
2008-12-01      253
2008-11-01      209
2007-12-01      172
2008-07-01      141
2008-06-01      124
2008-10-01      122
2008-05-01      115
2007-11-01      112
2007-10-01      105
2008-08-01      100
2007-08-01       74
2007-07-01       63
2008-09-01       57
2007-09-01       53
2007-06-01       24
Name: count, dtype: int64

To make the `issue_d` field more useful for modeling, we convert it from a raw datetime into a numerical feature representing the number of months since the loan’s issue date (using December 2017 as the reference point).

In [ ]:
reference_date = datetime(2017, 12, 1)

df["months_since_issue_date"] = (reference_date - df["issue_d"]).dt.days / 30.44

In [ ]:
df["months_since_issue_date"].describe().round()

count    466285.0
mean         51.0
std          14.0
min          36.0
25%          41.0
50%          47.0
75%          57.0
max         126.0
Name: months_since_issue_date, dtype: float64

In [ ]:
df["earliest_cr_line"].value_counts().head()

earliest_cr_line
Oct-2000    3674
Aug-2000    3597
Aug-2001    3455
Oct-1999    3406
Oct-2001    3329
Name: count, dtype: int64

In [ ]:
df["earliest_cr_line"] = pd.to_datetime(df["earliest_cr_line"], format="%b-%Y")
df["earliest_cr_line"].value_counts().head()

earliest_cr_line
2000-10-01    3674
2000-08-01    3597
2001-08-01    3455
1999-10-01    3406
2001-10-01    3329
Name: count, dtype: int64

In [ ]:
df["months_since_earliest_cr_line"] = (reference_date - df["earliest_cr_line"]).dt.days / 30.44

In [ ]:
df["months_since_earliest_cr_line"].describe()

count    466256.000000
mean        242.479543
std          86.921778
min          72.996058
25%         184.001314
50%         225.952694
75%         285.019711
max         886.925099
Name: months_since_earliest_cr_line, dtype: float64

In [ ]:
df.to_csv("processed-data/loan_data_processed.csv", index=False)